"""
Plan generator for document authoring.

Uses an LLM to generate action plan trees from high-level prompts,
producing structured plans that can be reviewed before execution.
"""

from __future__ import annotations

import json
import time
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from pydantic import BaseModel, Field

from officeplane.components.planning.models import (
    ActionNode,
    ActionPlan,
    GeneratePlanInput,
    GeneratePlanOutput,
    PlanSummary,
)


@runtime_checkable
class LLMProtocol(Protocol):
    """Protocol for LLM adapters (same as in runner.py)."""

    async def chat(
        self,
        messages: List[Dict[str, Any]],
        tools: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Send messages to the LLM."""
        ...


# Pydantic models for LLM-generated outlines


class PageSpec(BaseModel):
    """Specification for a page in the outline."""

    title: str = Field(..., description="Page title/topic")
    content_outline: str = Field("", description="Brief outline of what the page covers")


class SectionSpec(BaseModel):
    """Specification for a section in the outline."""

    title: str = Field(..., description="Section title")
    description: str = Field("", description="Brief description of section content")
    pages: List[PageSpec] = Field(default_factory=list)


class ChapterSpec(BaseModel):
    """Specification for a chapter in the outline."""

    title: str = Field(..., description="Chapter title")
    description: str = Field("", description="Brief description of chapter content")
    sections: List[SectionSpec] = Field(default_factory=list)


class DocumentSpec(BaseModel):
    """Complete document specification generated by LLM."""

    title: str = Field(..., description="Document title")
    author: Optional[str] = Field(None, description="Author name if specified")
    description: str = Field("", description="Document description/summary")
    chapters: List[ChapterSpec] = Field(default_factory=list)


SYSTEM_PROMPT = """You are a document planning assistant. Your task is to create detailed outlines for documents based on user requests.

When given a request, generate a structured JSON outline with the following format:

{
    "title": "Document Title",
    "author": null,
    "description": "Brief description of the document",
    "chapters": [
        {
            "title": "Chapter Title",
            "description": "What this chapter covers",
            "sections": [
                {
                    "title": "Section Title",
                    "description": "What this section covers",
                    "pages": [
                        {
                            "title": "Page Title",
                            "content_outline": "Key points to cover on this page"
                        }
                    ]
                }
            ]
        }
    ]
}

Guidelines:
- Create logical, well-organized document structures
- Each chapter should have a clear theme
- Sections should break down the chapter topic into manageable parts
- Pages should cover specific, focused topics
- Provide enough detail in content_outline for later content generation
- Keep titles concise but descriptive
- Ensure proper hierarchy: Document → Chapters → Sections → Pages

Respond with ONLY the JSON structure, no additional text."""


EDIT_SYSTEM_PROMPT = """You are a document editing assistant. Your task is to generate action plans for modifying existing documents.

Given a document outline and a user request, generate a JSON array of actions to perform.

Available actions:
- add_chapter: Add a new chapter to the document
- add_section: Add a new section to a chapter
- write_page: Write content to a new page in a section
- edit_page: Edit an existing page's content
- delete_page: Delete an existing page

IMPORTANT: When an action needs the ID from a previous action (like writing to a newly created section), use the placeholder format: "$node_N.id" where N is the index of the previous action (0-based).

Output format - a JSON object with an "actions" array:
{
    "actions": [
        {
            "action": "add_section",
            "chapter_id": "e67fef88-7dd8-4771-b5f7-6c0a4fdb3611",
            "title": "New Section Title",
            "description": "What this section covers"
        },
        {
            "action": "write_page",
            "section_id": "$node_0.id",
            "content": "The actual content to write on this page"
        }
    ]
}

Guidelines:
- Reference existing IDs from the document outline (UUIDs like "e67fef88-7dd8-...")
- Use "$node_N.id" to reference the output ID of action at index N (for newly created items)
- For new content, include the actual text content in the "content" field
- Only include actions that are necessary to fulfill the user's request
- Keep it minimal - don't add unnecessary structure

Respond with ONLY the JSON, no additional text."""


class PlanGenerator:
    """
    Generates action plan trees from high-level prompts.

    Uses an LLM to create document outlines, then converts them
    to ActionPlan trees with proper placeholder dependencies.
    """

    def __init__(self, llm: LLMProtocol) -> None:
        """
        Initialize the generator.

        Args:
            llm: LLM adapter implementing LLMProtocol
        """
        self.llm = llm

    async def generate_plan(self, input: GeneratePlanInput) -> GeneratePlanOutput:
        """
        Generate an action plan from a high-level prompt.

        Args:
            input: Generation parameters including the prompt

        Returns:
            GeneratePlanOutput with the plan or error
        """
        start_time = time.time()

        try:
            # Generate outline from LLM
            outline = await self._generate_outline(input)

            # Convert outline to action plan
            plan = self._outline_to_plan(outline, input.prompt)

            elapsed_ms = int((time.time() - start_time) * 1000)

            return GeneratePlanOutput(
                plan=plan,
                success=True,
                generation_time_ms=elapsed_ms,
            )

        except Exception as e:
            elapsed_ms = int((time.time() - start_time) * 1000)
            return GeneratePlanOutput(
                plan=ActionPlan(title="Failed Plan", original_prompt=input.prompt),
                success=False,
                error=str(e),
                generation_time_ms=elapsed_ms,
            )

    async def generate_edit_plan(
        self,
        document_outline: str,
        user_request: str,
        document_id: str,
        document_title: str,
    ) -> GeneratePlanOutput:
        """
        Generate an action plan for editing an existing document.

        Args:
            document_outline: Text representation of the existing document structure
            user_request: What the user wants to do
            document_id: ID of the document being edited
            document_title: Title of the document

        Returns:
            GeneratePlanOutput with the edit plan
        """
        start_time = time.time()

        try:
            user_message = f"""Document outline:
{document_outline}

User request:
{user_request}

Generate the action plan JSON:"""

            messages = [
                {"role": "system", "content": EDIT_SYSTEM_PROMPT},
                {"role": "user", "content": user_message},
            ]

            # Call LLM
            response = await self.llm.chat(messages, tools=[])

            content = response.get("content", "")
            if not content:
                raise ValueError("LLM returned empty response")

            # Parse JSON from response
            actions_data = self._extract_json(content)
            actions_list = actions_data.get("actions", [])

            if not actions_list:
                raise ValueError("LLM returned no actions")

            # Convert actions to ActionPlan
            plan = self._actions_to_plan(actions_list, document_id, document_title, user_request)

            elapsed_ms = int((time.time() - start_time) * 1000)

            return GeneratePlanOutput(
                plan=plan,
                success=True,
                generation_time_ms=elapsed_ms,
            )

        except Exception as e:
            elapsed_ms = int((time.time() - start_time) * 1000)
            return GeneratePlanOutput(
                plan=ActionPlan(title=f"Edit Plan for {document_title}", original_prompt=user_request),
                success=False,
                error=str(e),
                generation_time_ms=elapsed_ms,
            )

    def _actions_to_plan(
        self,
        actions: List[Dict[str, Any]],
        document_id: str,
        document_title: str,
        original_prompt: str,
    ) -> ActionPlan:
        """Convert a list of action dicts to an ActionPlan tree."""
        roots: List[ActionNode] = []

        # Track created nodes for parent references
        chapter_nodes: Dict[str, ActionNode] = {}
        section_nodes: Dict[str, ActionNode] = {}

        for idx, action in enumerate(actions):
            action_type = action.get("action", "")
            node_id = f"node_{idx}"

            if action_type == "add_chapter":
                node = ActionNode(
                    id=node_id,
                    action_name="add_chapter",
                    description=action.get("description", f"Add chapter: {action.get('title', '')}"),
                    inputs={
                        "document_id": document_id,
                        "title": action.get("title", "New Chapter"),
                        "order_index": len(roots),
                    },
                    parent_id=None,
                    children=[],
                    order_index=len(roots),
                )
                roots.append(node)
                chapter_nodes[node_id] = node

            elif action_type == "add_section":
                chapter_id = action.get("chapter_id", "")
                node = ActionNode(
                    id=node_id,
                    action_name="add_section",
                    description=action.get("description", f"Add section: {action.get('title', '')}"),
                    inputs={
                        "chapter_id": chapter_id,
                        "title": action.get("title", "New Section"),
                        "order_index": 0,
                    },
                    parent_id=None,
                    children=[],
                    order_index=idx,
                )
                roots.append(node)
                section_nodes[node_id] = node

            elif action_type == "write_page":
                section_id = action.get("section_id", "")
                content = action.get("content", "")
                node = ActionNode(
                    id=node_id,
                    action_name="write_page",
                    description=f"Write page content",
                    inputs={
                        "section_id": section_id,
                        "page_number": 1,
                        "content": content,
                    },
                    parent_id=None,
                    children=[],
                    order_index=idx,
                )
                roots.append(node)

            elif action_type == "edit_page":
                page_id = action.get("page_id", "")
                content = action.get("content", "")
                node = ActionNode(
                    id=node_id,
                    action_name="edit_page",
                    description=f"Edit page content",
                    inputs={
                        "page_id": page_id,
                        "content": content,
                    },
                    parent_id=None,
                    children=[],
                    order_index=idx,
                )
                roots.append(node)

            elif action_type == "delete_page":
                page_id = action.get("page_id", "")
                node = ActionNode(
                    id=node_id,
                    action_name="delete_page",
                    description=f"Delete page",
                    inputs={
                        "page_id": page_id,
                    },
                    parent_id=None,
                    children=[],
                    order_index=idx,
                )
                roots.append(node)

        return ActionPlan(
            title=f"Edit Plan for {document_title}",
            original_prompt=original_prompt,
            roots=roots,
        )

    async def _generate_outline(self, input: GeneratePlanInput) -> DocumentSpec:
        """Generate a document outline using the LLM."""
        # Build the user message with constraints
        user_message = f"""Create a detailed outline for the following request:

"{input.prompt}"

Constraints:
- Maximum {input.max_chapters} chapters
- Maximum {input.max_sections_per_chapter} sections per chapter
- Maximum {input.max_pages_per_section} pages per section
{"- Include detailed content outlines for each page" if input.include_content_outlines else ""}

Generate the JSON outline:"""

        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ]

        # Call LLM (no tools needed for outline generation)
        response = await self.llm.chat(messages, tools=[])

        # Extract content
        content = response.get("content", "")
        if not content:
            raise ValueError("LLM returned empty response")

        # Parse JSON from response
        outline_data = self._extract_json(content)

        # Validate and parse into DocumentSpec
        outline = DocumentSpec.model_validate(outline_data)

        # Apply limits
        outline = self._apply_limits(outline, input)

        return outline

    def _extract_json(self, content: str) -> Dict[str, Any]:
        """Extract JSON from LLM response, handling markdown code blocks."""
        content = content.strip()

        # Try to extract from markdown code block
        if "```json" in content:
            start = content.find("```json") + 7
            end = content.find("```", start)
            if end > start:
                content = content[start:end].strip()
        elif "```" in content:
            start = content.find("```") + 3
            end = content.find("```", start)
            if end > start:
                content = content[start:end].strip()

        try:
            return json.loads(content)
        except json.JSONDecodeError as e:
            raise ValueError(f"Failed to parse LLM response as JSON: {e}")

    def _apply_limits(self, outline: DocumentSpec, input: GeneratePlanInput) -> DocumentSpec:
        """Apply the input constraints to the generated outline."""
        # Limit chapters
        outline.chapters = outline.chapters[:input.max_chapters]

        for chapter in outline.chapters:
            # Limit sections per chapter
            chapter.sections = chapter.sections[:input.max_sections_per_chapter]

            for section in chapter.sections:
                # Limit pages per section
                section.pages = section.pages[:input.max_pages_per_section]

        return outline

    def _outline_to_plan(self, outline: DocumentSpec, original_prompt: str) -> ActionPlan:
        """Convert a DocumentSpec outline to an ActionPlan tree."""
        roots: List[ActionNode] = []

        # Create document node
        doc_node_id = "node_doc"
        doc_node = ActionNode(
            id=doc_node_id,
            action_name="create_document",
            description=f"Create document: {outline.title}",
            inputs={
                "title": outline.title,
                "author": outline.author,
            },
            parent_id=None,
            children=[],
            order_index=0,
        )

        # Create chapter nodes
        for ch_idx, chapter in enumerate(outline.chapters):
            ch_node_id = f"node_ch{ch_idx}"
            ch_node = ActionNode(
                id=ch_node_id,
                action_name="add_chapter",
                description=chapter.description or f"Add chapter: {chapter.title}",
                inputs={
                    "document_id": f"${doc_node_id}.id",
                    "title": chapter.title,
                    "order_index": ch_idx,
                },
                parent_id=doc_node_id,
                children=[],
                order_index=ch_idx,
            )

            # Create section nodes
            for sec_idx, section in enumerate(chapter.sections):
                sec_node_id = f"node_ch{ch_idx}_sec{sec_idx}"
                sec_node = ActionNode(
                    id=sec_node_id,
                    action_name="add_section",
                    description=section.description or f"Add section: {section.title}",
                    inputs={
                        "chapter_id": f"${ch_node_id}.id",
                        "title": section.title,
                        "order_index": sec_idx,
                    },
                    parent_id=ch_node_id,
                    children=[],
                    order_index=sec_idx,
                )

                # Create page nodes
                for pg_idx, page in enumerate(section.pages):
                    pg_node_id = f"node_ch{ch_idx}_sec{sec_idx}_pg{pg_idx}"
                    pg_node = ActionNode(
                        id=pg_node_id,
                        action_name="write_page",
                        description=page.content_outline or f"Write page: {page.title}",
                        inputs={
                            "section_id": f"${sec_node_id}.id",
                            "page_number": pg_idx + 1,
                            "title": page.title,
                            "content_outline": page.content_outline,
                        },
                        parent_id=sec_node_id,
                        children=[],
                        order_index=pg_idx,
                    )
                    sec_node.children.append(pg_node)

                ch_node.children.append(sec_node)

            doc_node.children.append(ch_node)

        roots.append(doc_node)

        return ActionPlan(
            title=outline.title,
            original_prompt=original_prompt,
            roots=roots,
        )

    def generate_plan_sync(self, input: GeneratePlanInput) -> GeneratePlanOutput:
        """Synchronous version of generate_plan."""
        import asyncio
        return asyncio.run(self.generate_plan(input))


class GeminiPlanAdapter:
    """
    Google Gemini adapter for plan generation.

    Uses the google-generativeai SDK to generate document plans.
    """

    def __init__(self, api_key: str, model: str = "gemini-2.0-flash") -> None:
        """
        Initialize the adapter.

        Args:
            api_key: Google API key
            model: Gemini model to use
        """
        try:
            import google.generativeai as genai
            from google.generativeai.types import GenerationConfig

            self._genai = genai
            self._GenerationConfig = GenerationConfig
        except ImportError:
            raise ImportError(
                "google-generativeai is required. Install with: pip install google-generativeai"
            )

        self._api_key = api_key
        self._model_name = model
        self._client = None

    def _get_client(self):
        """Get or create the Gemini client."""
        if self._client is None:
            self._genai.configure(api_key=self._api_key)
            self._client = self._genai.GenerativeModel(
                model_name=self._model_name,
                generation_config=self._GenerationConfig(
                    response_mime_type="application/json",
                ),
            )
        return self._client

    async def chat(
        self,
        messages: List[Dict[str, Any]],
        tools: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Generate a plan using Gemini."""
        import asyncio

        # Build prompt from messages
        prompt_parts = []
        for msg in messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")
            if role == "system":
                prompt_parts.append(f"Instructions:\n{content}\n")
            elif role == "user":
                prompt_parts.append(f"Request:\n{content}\n")

        full_prompt = "\n".join(prompt_parts)

        try:
            client = self._get_client()

            # Run synchronous API call in thread pool
            response = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: client.generate_content(full_prompt),
            )

            raw_text = response.text if hasattr(response, "text") else ""

            return {
                "content": raw_text,
                "finish_reason": "stop",
            }

        except Exception as e:
            # Return error in a way the generator can handle
            raise ValueError(f"Gemini API error: {str(e)}")


class MockPlanLLM:
    """
    Mock LLM for testing plan generation without API calls.

    Generates a simple document outline based on the prompt.
    """

    def __init__(self, num_chapters: int = 3, num_sections: int = 2, num_pages: int = 1) -> None:
        """
        Initialize the mock.

        Args:
            num_chapters: Number of chapters to generate
            num_sections: Sections per chapter
            num_pages: Pages per section
        """
        self.num_chapters = num_chapters
        self.num_sections = num_sections
        self.num_pages = num_pages

    async def chat(
        self,
        messages: List[Dict[str, Any]],
        tools: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Generate a mock document outline."""
        # Extract topic from user message
        user_msg = next((m for m in messages if m["role"] == "user"), None)
        topic = "Sample Document"
        if user_msg:
            content = user_msg["content"]
            if '"' in content:
                # Extract text between quotes
                start = content.find('"') + 1
                end = content.find('"', start)
                if end > start:
                    topic = content[start:end]

        # Generate outline
        chapters: List[Dict[str, Any]] = []

        for ch_idx in range(self.num_chapters):
            sections: List[Dict[str, Any]] = []

            for sec_idx in range(self.num_sections):
                pages: List[Dict[str, str]] = []

                for pg_idx in range(self.num_pages):
                    page = {
                        "title": f"Page {pg_idx + 1}",
                        "content_outline": f"Content covering aspect {pg_idx + 1} of section {sec_idx + 1}",
                    }
                    pages.append(page)

                section: Dict[str, Any] = {
                    "title": f"Section {sec_idx + 1}.{ch_idx + 1}",
                    "description": f"Details about subtopic {sec_idx + 1}",
                    "pages": pages,
                }
                sections.append(section)

            chapter: Dict[str, Any] = {
                "title": f"Chapter {ch_idx + 1}: Topic {ch_idx + 1}",
                "description": f"Exploring topic {ch_idx + 1} in detail",
                "sections": sections,
            }
            chapters.append(chapter)

        outline: Dict[str, Any] = {
            "title": f"{topic}",
            "author": None,
            "description": f"A comprehensive guide to {topic.lower()}",
            "chapters": chapters,
        }

        return {
            "content": json.dumps(outline),
            "finish_reason": "stop",
        }


def create_plan_from_outline(
    title: str,
    original_prompt: str,
    chapters: List[Dict[str, Any]],
) -> ActionPlan:
    """
    Create an ActionPlan from a pre-defined outline structure.

    Useful for creating plans programmatically without LLM.

    Args:
        title: Document title
        original_prompt: Original user request
        chapters: List of chapter dicts with structure:
            {
                "title": str,
                "description": str,
                "sections": [
                    {
                        "title": str,
                        "description": str,
                        "pages": [
                            {"title": str, "content_outline": str}
                        ]
                    }
                ]
            }

    Returns:
        ActionPlan tree
    """
    outline = DocumentSpec(
        title=title,
        description=original_prompt,
        chapters=[
            ChapterSpec(
                title=ch.get("title", f"Chapter {i+1}"),
                description=ch.get("description", ""),
                sections=[
                    SectionSpec(
                        title=sec.get("title", f"Section {j+1}"),
                        description=sec.get("description", ""),
                        pages=[
                            PageSpec(
                                title=pg.get("title", f"Page {k+1}"),
                                content_outline=pg.get("content_outline", ""),
                            )
                            for k, pg in enumerate(sec.get("pages", []))
                        ],
                    )
                    for j, sec in enumerate(ch.get("sections", []))
                ],
            )
            for i, ch in enumerate(chapters)
        ],
    )

    generator = PlanGenerator.__new__(PlanGenerator)
    return generator._outline_to_plan(outline, original_prompt)
